### ISSUE TITLE
Send explicit OnApplicationEnd event to plugins

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/atum#25]
## Background
Atum plugins are event listeners. But some plugins need to finalize their states when the application ends. For instance, the Kafka control info plugin needs to close the producer at the end of executions. But Atum currently does not provide the means to identify when the last update checkpoint event is sent.

## Feature
Plugins need to know which event is the last time so they can finalize (close resources for instance).

Add an additional event to the event listener. Let's call it `onApplicationEnd`

**Comment by benedeki** [comment]
Can the originating system know, it's a final message?
There are many preconditions for such knowledge.
Is it s sole producer or is it aware of rest of the system? 🤔

**Comment by yruslan** [comment]
Atum subscribes to Spark events. And the last event that happens is `onApplicationEnd()`. Atum double checks that all plugins know about all checkpoints, and if not, calls `onUpdateCheckpoints()` on plugins. But from the timeline it happens after the execution if `main()`.

So, yes, we know that this is the final message Spark sends. We can forward the message to Atum plugins so they can finalize themselves if needed.
