### ISSUE TITLE
Initial Info file creation tool

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/atum#6]
Create an initial info file creation tool as a separate project inside an examples folder inside this repository. This tool will be a example and a template for Spark applications for creating initial info files.

**Comment by Praveen456B** [comment]
you mean to say need to be create separate project for info file? does info file create automatically based on the input csv file?

Please do help me to understand _INFO file concept!!

Thanks

**Comment by yruslan** [comment]
Atum is designed to track accuracy and completeness of critical fields/columns of the data as it passes through Hadoop/Spark pipeline. It does this by maintaining a set of checkpoints consisting of sets of hashsums of selected columns (we call them 'metrics'). This information is saved in JSON format to a file called `_INFO` inside dataset directory.

An info file defines which fields need to be tracked and what hashsum values did these fields have at time of checkpoint creation. Atum provides routines for Spark that allows you to read a source data file with its info file, and create checkpoints. To do that Atum reads an existing info file and follows its definition of metrics each time a new checkpoint is created.

For Atum an info file is an interface. It always expects it to be already created when you process Atum controlled data in Spark. Since most of the time the source of the data is not Hadoop the initial info file is created by technologies available to the source system. But tor testing purposes and for a very rare occasions when data originates from Hadoop, an initial info file creation tool is helpful. It can be used by our users as a starting point for creating info files according to their particular use case requirements.

**Comment by Praveen456B** [comment]
Thanks for your details explain
