### ISSUE TITLE
Add ability to prepend a Checkpoint

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/atum#75]
Add ability to prepend a `Checkpoint` to `ControlMeasure` and in builder with `withPreceedingChekpoint(checkpoint)`

**Comment by dk1844** [comment]
I believe the first checkpoint usually has `order = 1`. Should we check/warn if this is the case or do should we just allow users to use the model in any way they like (that is possible)

**Comment by dk1844** [comment]
Implemented in #76.
