### ISSUE TITLE
Create accessor for Control Measure and other models from the atum context

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/atum#93]
Create an accessor for Control Measure and other models from the Atum context.
At the point it can be on `spark` or `df`
- `spark.getControlMeasures`
- `spark.getAdditionalInfo("key")`
- `spark.getAllAdditionalInfo`

Not really sure right now what makes the most sense. The `getControlMeasure` which is the parent model of everything is the minimal output of this task.

**Comment by dk1844** [comment]
I understand the need for the `getControlMeasure` accessor, it will be really useful. 

As for the other methods wrapper methods `getAllAdditionalInfo`, `getAdditionalInfo("key")` unless I am missing an important point, I am not a fan. Calling simply `getControlMeasure.metadata.additionalInfo` / `getControlMeasure.metadata.additionalInfo.get(key)` would do fine. Also we don't wrap other fields of the ControlMeasure this way. In case we decide that it is actually desired, maybe just adding the `getAllAdditionalInfo` could be sound compromise?
