### ISSUE TITLE
Enable user to specify measurement controlType

### ISSUE THREAD

**Issue by MatloaItumeleng** [AbsaOSS/atum#97]
Enable user to chose which aggregate (AggregatedTotal, AbsAggregatedTotal or HashCrc32) is Atum supposed to use for a given input column, this is for method "withAggregateColumns".

**Use case**: In a scenario where input for aggregate column generates controlType.HashCrc32 whereas requirement to match with metrics received from control file from source , user needs to choose which aggregate Atum is supposed use for the aggregate column.

**Comment by dk1844** [comment]
Hi @MatloaItumeleng, thanks for submitting this idea. I understand the current behavior of the ControlMeasureBuilder does not suit you (in essence, now:  for numeric types `controlType.absAggregatedTotal`;for non-numeric `controlType.HashCrc32` is chosen.)

So what granularity of the setup do you need? I understand that you want to choose the controlType, but is it sufficient to specify a common `controlType` for all columns in `aggregateColumns` to create the control counts? Or do you imagine that there will need to be a specific `controlType` set for every column in `aggregateColumns`?

**Comment by MatloaItumeleng** [comment]
Hi @dk1844,  for this use case one column is currently being passed in the aggrigateColumns  where I'd like to select one controlType (for this instance AggregateTotal )  which will be used when I pass  it in ControlMeasureBuilder.forDF(df).withAggregateColumns
